pages:
  - name: Home
    buttons:
      - entity_id: light.living_room_lights_z2m
        service: light.toggle
        text: "Living room\nlights"
      - entity_id: light.bedroom_lights_z2m
        service: light.toggle
        text: "Bedroom\nlights"
      - entity_id: light.guest_room
        service: light.toggle
        text: "Guest room\nlight"
      - entity_id: light.outside_lights_z2m
        service: light.toggle
        text: "Outside\nlights"
      - entity_id: switch.space_heater
        service: switch.toggle
        text: '{{ states("switch.space_heater") }}'
        icon: "space-heater.png"
        text_size: 16
        text_color: black
        icon_gray_when_off: true
      - entity_id: media_player.kef_ls50
        service: media_player.volume_set
        service_data:
          volume_level: '{{ max(state_attr("media_player.kef_ls50", "volume_level") - 0.05, 0) }}'
          entity_id: media_player.kef_ls50
        text: '{{ (100 * state_attr("media_player.kef_ls50", "volume_level")) | int }}%'
        text_size: 16
        icon_mdi: "volume-minus"
      - entity_id: media_player.kef_ls50
        service: media_player.volume_set
        service_data:
          volume_level: '{{ min(state_attr("media_player.kef_ls50", "volume_level") + 0.05, 1) }}'
          entity_id: media_player.kef_ls50
        text: '{{ (100 * state_attr("media_player.kef_ls50", "volume_level")) | int }}%'
        text_size: 16
        icon_mdi: volume-plus
      - service: script.reset_manual_control
        text: "Reset\nadaptive\nlighting"
      - icon: night_sky.png
        service: script.turn_off_everything
        text: ALL OFF
      - entity_id: input_select.sleep_mode
        service: input_select.select_previous
        text: Sleep {{ states("input_select.sleep_mode") }}
        icon_mdi: power-sleep
      - icon: fireplace.png
        service: script.start_fireplace_netflix
      - service_data:
          playlist: 37i9dQZF1DXaRycgyh6kXP
          source: KEF LS50
        icon: spotify.png
        service: script.start_spotify
      - icon: hogwarts.png
        service: script.start_hogwarts_legacy
      - special_type: previous-page
      - special_type: next-page
  - name: Media
    buttons:
      - icon: netflix.png
        service: script.start_spotify
      - icon: xbox.png
        service: script.start_xbox
      - special_type: empty
      - special_type: empty
      - special_type: empty
      - special_type: empty
      - special_type: empty
      - special_type: empty
      - special_type: empty
      - special_type: empty
      - special_type: empty
      - special_type: empty
      - entity_id: light.guest_room
        service: light.toggle
        text: "Guest room\nlight"
      - special_type: previous-page
      - special_type: next-page
