name: docker

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
          - linux/arm/v7
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Replace slashes in tag
        run: |
          TAG=basnijholt/home-assistant-streamdeck-yaml:${{ matrix.platform }}
          NEW_TAG=$(echo $TAG | sed 's/\//-/g')
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: ${{ matrix.platform }}
          tags: ${{ env.NEW_TAG }}

  manifest:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: basnijholt
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create and push manifest
        run: |
          PLATFORMS="linux-amd64,linux-arm64,linux-arm-v7"
          docker manifest create basnijholt/home-assistant-streamdeck-yaml:latest \
            basnijholt/home-assistant-streamdeck-yaml:linux-amd64 \
            basnijholt/home-assistant-streamdeck-yaml:linux-arm64 \
            basnijholt/home-assistant-streamdeck-yaml:linux-arm-v7
          docker manifest push basnijholt/home-assistant-streamdeck-yaml:latest
